/* Builds data/atlas/stats.js: five country indicators for the 46 Atlas
 * countries from one source, the IMF World Economic Outlook, through the
 * IMF DataMapper API. One source for every country keeps the world map's
 * colours comparable. Run by hand when a new WEO is out:
 *
 *   node tools/atlas-stats.js [year]      (default: the year before today's)
 *
 * The figures for the current year in a WEO are partly estimates; the
 * page says which edition and year it shows. */
const fs = require('fs'), path = require('path'), https = require('https'), vm = require('vm');
const ROOT = path.join(__dirname, '..');
const YEAR = String(process.argv[2] || new Date().getFullYear() - 1);
const ISO3 = { PT: 'PRT', ES: 'ESP', FR: 'FRA', MT: 'MLT', IT: 'ITA', CH: 'CHE', IS: 'ISL', IE: 'IRL', GB: 'GBR', DK: 'DNK',
  BE: 'BEL', LU: 'LUX', NL: 'NLD', AT: 'AUT', DE: 'DEU', NO: 'NOR', SE: 'SWE', FI: 'FIN', PL: 'POL', LT: 'LTU', EE: 'EST',
  CZ: 'CZE', GR: 'GRC', RO: 'ROU', BG: 'BGR', US: 'USA', CA: 'CAN', RU: 'RUS', TR: 'TUR', IL: 'ISR', SA: 'SAU', OM: 'OMN',
  QA: 'QAT', KW: 'KWT', AE: 'ARE', MY: 'MYS', TH: 'THA', SG: 'SGP', VN: 'VNM', TW: 'TWN', CN: 'CHN', AU: 'AUS', NZ: 'NZL',
  JP: 'JPN', KR: 'KOR', HK: 'HKG' };
const IND = { gdppc: 'PPPPC', gdp: 'NGDPD', pop: 'LP', unemp: 'LUR', growth: 'NGDP_RPCH' };
const get = (u) => new Promise((ok, no) => https.get(u, { headers: { 'User-Agent': 'curl/8.0', Accept: 'application/json' } }, (r) => { let b = ''; r.on('data', (d) => b += d); r.on('end', () => { try { ok(JSON.parse(b)); } catch (e) { no(e); } }); }).on('error', no));

(async () => {
  const meta = (await get('https://www.imf.org/external/datamapper/api/v1/indicators')).indicators;
  const out = {};
  for (const [k, code] of Object.entries(IND)) {
    const v = (await get('https://www.imf.org/external/datamapper/api/v1/' + code + '?periods=' + YEAR)).values[code];
    for (const [id, i3] of Object.entries(ISO3)) {
      const x = v[i3] && v[i3][YEAR];
      (out[id] = out[id] || {})[k] = x == null ? null : Math.round(x * 100) / 100;
    }
  }
  const edition = meta.PPPPC.source; /* "World Economic Outlook (April 2026)" */
  const ctx = { window: {} }; ctx.window = ctx; vm.createContext(ctx);
  vm.runInContext(fs.readFileSync(path.join(ROOT, 'data/atlas/index.js'), 'utf8'), ctx);
  const missing = ctx.ATLAS.countries.filter((c) => !out[c.id]).map((c) => c.id);
  if (missing.length) throw new Error('no ISO3 for ' + missing);
  const body = '/* ---------------------------------------------------------------------------\n' +
    ' * Country indicators for the Atlas. GENERATED by tools/atlas-stats.js — do not edit.\n' +
    ' *\n * IMF, ' + edition + ', through the IMF DataMapper API, for ' + YEAR + ' (partly\n' +
    ' * estimates). null: the IMF publishes no figure (the WEO has no unemployment\n' +
    ' * rate for the Gulf states).\n' +
    ' *   gdppc   GDP per head, PPP, international dollars\n' +
    ' *   gdp     GDP, current prices, billions of US dollars\n' +
    ' *   pop     population, millions\n' +
    ' *   unemp   unemployment rate, % of the labour force\n' +
    ' *   growth  real GDP growth, % a year\n' +
    ' * ------------------------------------------------------------------------- */\n\n' +
    'window.ATLAS_STATS = ' + JSON.stringify({
      source: 'IMF, ' + edition, year: +YEAR, seen: new Date().toISOString().slice(0, 10),
      src: 'https://www.imf.org/external/datamapper/datasets/WEO', tag: 'data', values: out
    }, null, 1).replace(/\n\s*/g, ' ') + ';\n';
  fs.writeFileSync(path.join(ROOT, 'data/atlas/stats.js'), body);
  console.log('wrote data/atlas/stats.js for', YEAR, edition);
})().catch((e) => { console.error(e); process.exit(1); });
