#!/usr/bin/env node
/* ---------------------------------------------------------------------------
 * The sources behind each country's "Visas and permits" section.
 *
 *   node tools/visas-sources.js          rewrite every data/atlas/visas/<id>.js
 *   node tools/visas-sources.js de fr    only these
 *   node tools/visas-sources.js --check  change nothing; list files out of step
 *
 * A visa file (data/atlas/visas/<id>.js) cites sources by the ids of the
 * country's register in the research library, e.g. DE-SRC-21 in
 * research/visas_immigration/germany/germany_sources.md. This tool reads that
 * register and writes, at the foot of the visa file, the title, link and date
 * of every id the file cites, so the page can list them and the register stays
 * the one place a source is described. The registers are tables written by
 * several hands, with different columns; the columns are found by their
 * headings.
 *
 * Also exported for tests/atlas-test.js: register(folder), block(file).
 * ------------------------------------------------------------------------- */

'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const LIB = path.join(ROOT, 'research/visas_immigration');
const DIR = path.join(ROOT, 'data/atlas/visas');
const MARK = '/* Sources: generated by tools/visas-sources.js';

const ID = /([A-Z]{2,3}-SRC-\d+[A-Za-z]?)/;
const ITALIAN = /\b(Repubblica|Governo|Ministero|Parlamento|Stato|Consiglio|Federazione|Confederazione|Presidente|Sultano|Granducato|Gazzetta|Assemblea|Comitato|Unione Europea|Amīr|Regno|Ufficio|Conferenza|Ministri|Ambasciat\w*|Cina|Cancelleria|Dipartimento)\b/;

/* Markdown cell to plain text. */
function plain(s) {
  return s.replace(/\[([^\]]*)\]\(([^)]*)\)/g, '$1').replace(/[*`]/g, '').replace(/\$\\le\$/g, '≤').replace(/\$\\ge\$/g, '≥')
    .replace(/<br\s*\/?>/gi, ' ').replace(/\s+/g, ' ').trim();
}
function urlOf(cell) {
  const md = /\]\((https?:\/\/[^)\s]+)\)/.exec(cell);
  if (md) return md[1];
  const bare = /(https?:\/\/[^\s`|)>\]]+)/.exec(cell);
  if (bare) return bare[1].replace(/[.,;]+$/, '');
  return null;
}
function dateOf(cell) {
  let m = /(\d{4})-(\d{2})-(\d{2})/.exec(cell);
  if (m) return m[1] + '-' + m[2] + '-' + m[3];
  m = /(\d{1,2})[/.](\d{1,2})[/.](\d{4})/.exec(cell);
  if (m) return m[3] + '-' + String(m[2]).padStart(2, '0') + '-' + String(m[1]).padStart(2, '0');
  return null;
}
/* A long description is cut at its first dash or semicolon. */
function short(s, max) {
  if (s.length <= max) return s;
  const cut = s.search(/ [–—-] |; /);
  if (cut > 20 && cut <= max) return s.slice(0, cut);
  return s.slice(0, max - 1).replace(/\s+\S*$/, '') + '…';
}

/* id → [title, url, date] for a country folder's register. */
function register(folder) {
  const file = path.join(LIB, folder, folder + '_sources.md');
  const out = {};
  let head = null;
  fs.readFileSync(file, 'utf8').split('\n').forEach((line) => {
    if (!/^\s*\|/.test(line)) { head = head && /^\s*$/.test(line) ? head : head; return; }
    const cells = line.trim().replace(/^\||\|$/g, '').split('|').map((c) => c.trim());
    if (/ID/i.test(cells[0]) && !ID.test(cells[0])) { head = cells.map(plain); return; }
    const m = ID.exec(cells[0]);
    if (!m || !head) return;
    const col = (re, not) => head.findIndex((h, i) => i > 0 && re.test(h) && (!not || not.indexOf(i) < 0));
    const issuer = col(/^(Ente|Istituzione|Autorit|Ente Emittente)/i);
    let title = col(/Denominazione|Titolo|Atto|Documento|Descrizione|Pubblicazione/i, [issuer]);
    if (title < 0) title = col(/Oggetto/i, [issuer]);
    const url = col(/URL/i), when = col(/^Data/i);
    /* An issuer's gloss in Italian, "BAMF (Ufficio Federale …)", is dropped. */
    const who = issuer > 0 ? plain(cells[issuer] || '').replace(/\s*\(([^)]*)\)/g, (m, x) => ITALIAN.test(x) ? '' : m) : '';
    const what = title > 0 ? plain(cells[title] || '') : '';
    let name = short(what, 120);
    /* The issuer leads the title unless it is a description in Italian
     * ("Repubblica Federale di Germania"): the English page shows names. */
    if (who && !ITALIAN.test(who) && name.toLowerCase().indexOf(who.toLowerCase()) < 0) name = short(who, 60) + ': ' + name;
    const link = (url > 0 && urlOf(cells[url] || '')) || cells.map(urlOf).filter(Boolean)[0] || null;
    out[m[1]] = [name || m[1], link, (when > 0 && dateOf(cells[when] || '')) || null];
  });
  return out;
}

/* The ids a visa file cites, in order of first use. */
function cited(src) {
  const body = src.indexOf(MARK) >= 0 ? src.slice(0, src.indexOf(MARK)) : src;
  const ids = [];
  (body.match(/[A-Z]{2,3}-SRC-\d+[A-Za-z]?/g) || []).forEach((id) => { if (ids.indexOf(id) < 0) ids.push(id); });
  return ids;
}
function folderOf(src) {
  const m = /folder:\s*'([a-z_]+)'/.exec(src);
  return m && m[1];
}
function countryOf(src) {
  const m = /ATLAS\.addVisas\(\{\s*id:\s*'([A-Z]{2})'/.exec(src);
  return m && m[1];
}

/* The generated foot of a visa file, from its own text. */
function block(src) {
  const folder = folderOf(src), id = countryOf(src);
  const reg = register(folder), checked = (/checked:\s*'([\d-]+)'/.exec(src) || [])[1];
  const lines = cited(src).map((k) => {
    const r = reg[k];
    if (!r) return '  ' + JSON.stringify(k) + ': null';
    return '  ' + JSON.stringify(k) + ': ' + JSON.stringify([r[0], r[1], r[2] || checked]);
  });
  return MARK + ' from research/visas_immigration/' + folder + '/' + folder + '_sources.md.\n' +
    ' * Do not edit by hand: change the register, then run the tool. */\n' +
    'ATLAS.visaSources(\'' + id + '\', {\n' + lines.join(',\n') + '\n});\n';
}
function rewrite(src) {
  const head = src.indexOf(MARK) >= 0 ? src.slice(0, src.indexOf(MARK)).replace(/\s*$/, '\n\n') : src.replace(/\s*$/, '\n\n');
  return head + block(src);
}

module.exports = { register, block, rewrite, cited, MARK };

if (require.main === module) {
  const args = process.argv.slice(2);
  const check = args.includes('--check');
  const only = args.filter((a) => !a.startsWith('--')).map((a) => a.toLowerCase() + '.js');
  const files = fs.readdirSync(DIR).filter((f) => /^[a-z]{2}\.js$/.test(f) && (!only.length || only.includes(f)));
  let stale = 0;
  files.forEach((f) => {
    const p = path.join(DIR, f), src = fs.readFileSync(p, 'utf8'), next = rewrite(src);
    const missing = (/ATLAS\.visaSources\([\s\S]*$/.exec(next)[0].match(/"[^"]+": null/g) || []);
    if (missing.length) console.log(f + ': not in the register: ' + missing.join(' '));
    if (next === src) return;
    stale++;
    if (check) console.log(f + ': sources out of step with the register');
    else { fs.writeFileSync(p, next); console.log(f + ': sources written (' + cited(src).length + ')'); }
  });
  if (check && stale) process.exit(1);
}
